### ISSUE TITLE
-j not working on illumos

### ISSUE THREAD

**Issue by GernotS** [totalAldo/zxfer#1]
command "parallel" is unknown in Illumos and Solaris

**Comment by totalAldo** [comment]
@GernotS is gnu `parallel` available on those platforms? Without it, -j won't work. `xargs` mangles the output when running multiple processes hence the use of `parallel`

**Comment by GernotS** [comment]
after installing gnu parallel:

./zxfer -FvwV -j2 -T root@192.168.14.5 -R zones/7ff90f92-dcc3-c67f-d197-82308468e8fa copy/backup
Checking source snapshot.
Begin get_zfs_list()
New temporary file: /tmp/zxfer02mjq8
Running command in the background: /usr/sbin/zfs list -Hr -o name zones/7ff90f92-dcc3-c67f-d197-82308468e8fa | parallel -j 2 --line-buffer '/usr/sbin/zfs list -H -o name -s creation -t snapshot {}'
New temporary file: /tmp/zxfer36v9tn
New temporary file: /tmp/zxfer3irnan
Running command: sed -e 's|copy/backup/7ff90f92-dcc3-c67f-d197-82308468e8fa|zones/7ff90f92-dcc3-c67f-d197-82308468e8fa|g' /tmp/zxfer36v9tn | sort > /tmp/zxfer3irnan
Running command: /usr/bin/ssh -S /tmp/zxfer288llg root@192.168.14.5 /usr/sbin/zfs list -t filesystem,volume -Hr -o name copy/backup
Waiting for background processes to finish.
cannot open 'zones/7ff90f92-dcc3-c67f-d197-82308468e8fa': missing '@' delimiter in snapshot name
Background processes finished.
New temporary file: /tmp/zxfer126pod
Running command: sort /tmp/zxfer02mjq8 > /tmp/zxfer126pod
Source dataset count:        1
No snapshots to transfer.

Failed to retrieve snapshots from the source
Closing ssh control socket: /usr/bin/ssh -S /tmp/zxfer288llg -O exit root@192.168.14.5

**Comment by totalAldo** [comment]
@GernotS Thank you for the details. This may be due to `parallel`'s path not being used. I've updated the experimental branch to use `which parallel` to set its path.

**Comment by totalAldo** [comment]
@GernotS `parallel` was piping its output via `zstd` by default. The full path of `zstd` was not specified and they may have been the issue. When the `-z` or `-Z` options are not used, `parallel` no longer pipes the output through `zstd`. When you have a chance, can you try with the experimental branch of this repo and if it doesn't work, please share the output of -V? 

Thanks!

**Comment by totalAldo** [comment]
@GernotS what is the output of:

`/usr/sbin/zfs list -Hr -o name zones/7ff90f92-dcc3-c67f-d197-82308468e8fa | /opt/tools/bin/parallel -j 2 --line-buffer '/usr/sbin/zfs list -H -o name -s creation -t snapshot {}'
`

and 

`/opt/tools/bin/parallel --version`

Trying to figure out if `parallel` is working as expected on your system.

**Comment by GernotS** [comment]
/opt/tools/bin/parallel --version
GNU parallel 20230822

/usr/sbin/zfs list -Hr -o name zones/7ff90f92-dcc3-c67f-d197-82308468e8fa | /opt/tools/bin/parallel -j 2 --line-buffer '/usr/sbin/zfs list -H -o name -s creation -t snapshot {}'
cannot open 'zones/7ff90f92-dcc3-c67f-d197-82308468e8fa': missing '@' delimiter in snapshot name

**Comment by totalAldo** [comment]
@GernotS I installed IllumOS and discovered that in order to list the snapshots for one dataset, you have to pass `-d 1`

Please try the `experimental` branch and see if it works now.

Here's what I did to test `parallel`:

```
# Install IllumOS and configure networking

# Download and extract GNU Parallel (didn't find this using pkg search)
wget https://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2
tar -xjf parallel-latest.tar.bz2
cd parallel-20240722

# Build and install
./configure
make
sudo make install

# will be installed in /usr/local/bin/parallel

# test parallel
zfs list -Hr -o name -r rpool | /usr/local/bin/parallel -j 2 --line-buffer 'zfs list -H -o name -d 1 -s creation -t snap {}'
```

**Comment by GernotS** [comment]
experimental branch works!

**Comment by totalAldo** [comment]
@GernotS Awesome! I've merged the changes into the master branch. If you encounter any further issues, you know what to do! Thanks for your help.
