### ISSUE TITLE
latest version does not seem to populate list of destination snapshots on Illumos

### ISSUE THREAD

**Issue by GernotS** [totalAldo/zxfer#2]
resulting in attempt to full send instead of incremental

**Comment by totalAldo** [comment]
@GernotS can you try the experimental branch of this repo. I released some code clean up and refactoring just recently. If it doesn't, a snippet of the command you're using would help so I can test.

**Comment by GernotS** [comment]
this is what happens here:

./zxfer -FvwV -T root@192.168.14.5 -R zones/7ff90f92-dcc3-c67f-d197-82308468e8fa copy/backup
Checking source snapshot.
Begin get_zfs_list()
New temporary file: /tmp/zxfer2fmfqa
Executing command in the background: /usr/sbin/zfs list -Hr -o name -s creation -t snapshot zones/7ff90f92-dcc3-c67f-d197-82308468e8fa
New temporary file: /tmp/zxfer2e8abo
New temporary file: /tmp/zxfer2uacd9
Running command: sed -e 's|copy/backup/7ff90f92-dcc3-c67f-d197-82308468e8fa|zones/7ff90f92-dcc3-c67f-d197-82308468e8fa|g' /tmp/zxfer2e8abo | sort > /tmp/zxfer2uacd9
Running command: /usr/bin/ssh -S /tmp/zxfer2ic3lt root@192.168.14.5 /usr/sbin/zfs list -t filesystem,volume -Hr -o name copy/backup
Waiting for background processes to finish.
Background processes finished.
New temporary file: /tmp/zxfer08hofj
Running command: sort /tmp/zxfer2fmfqa > /tmp/zxfer08hofj
Source dataset count:        1
End get_zfs_list()
Begin get_last_common_snapshot()
End get_last_common_snapshot()
/usr/sbin/zfs send zones/7ff90f92-dcc3-c67f-d197-82308468e8fa@2024-07-28_10.03.00--3d | /usr/bin/ssh -S /tmp/zxfer2ic3lt root@192.168.14.5 "/usr/sbin/zfs receive -F copy/backup/7ff90f92-dcc3-c67f-d197-82308468e8fa"
cannot receive new filesystem stream: destination has snapshots (eg. copy/backup/7ff90f92-dcc3-c67f-d197-82308468e8fa@2024-03-05_07.17.00--1y)
must destroy them to overwrite it
Error when executing command.
Closing ssh control socket: /usr/bin/ssh -S /tmp/zxfer2ic3lt -O exit root@192.168.14.5

**Comment by GernotS** [comment]
old version (2024.04.09):

./zxfer -FvwV -T root@192.168.14.5 -R zones/7ff90f92-dcc3-c67f-d197-82308468e8fa copy/backup
Checking source snapshot.
Begin get_zfs_list()
New temporary file: /tmp/zxfer1tq92d
New temporary file: /tmp/zxfer2m0de1
Executing command in the background: /usr/sbin/zfs list -Hr -o name -s creation -t snapshot zones/7ff90f92-dcc3-c67f-d197-82308468e8fa
Executing command in the background: /usr/bin/ssh root@192.168.14.5 /usr/sbin/zfs list -Hr -o name -s creation -t snapshot copy/backup
Running command: /usr/bin/ssh root@192.168.14.5 /usr/sbin/zfs list -t filesystem,volume -H -o name -s creation
Running command: /usr/sbin/zfs list -t filesystem,volume -Hr -o name zones/7ff90f92-dcc3-c67f-d197-82308468e8fa
Running command: /usr/bin/ssh root@192.168.14.5 /usr/sbin/zfs list -t filesystem,volume -Hr -o name copy/backup
Waiting for background processes to finish.
Wait finished.
End get_zfs_list()
Begin set_last_common_snapshot()
Found last common snapshot: 2024-07-28_05.00.00--1d.
/usr/sbin/zfs send -v -w -I 2024-07-28_05.00.00--1d zones/7ff90f92-dcc3-c67f-d197-82308468e8fa@2024-07-28_10.03.00--3d | /usr/bin/ssh root@192.168.14.5 "/usr/sbin/zfs receive -F copy/backup/7ff90f92-dcc3-c67f-d197-82308468e8fa"
send from @2024-07-28_05.00.00--1d to zones/7ff90f92-dcc3-c67f-d197-82308468e8fa@2024-07-28_05.03.01--3d estimated size is 119M
send from @2024-07-28_05.03.01--3d to zones/7ff90f92-dcc3-c67f-d197-82308468e8fa@2024-07-28_06.03.00--3d estimated size is 686M
send from @2024-07-28_06.03.00--3d to zones/7ff90f92-dcc3-c67f-d197-82308468e8fa@2024-07-28_07.03.01--3d estimated size is 782M
send from @2024-07-28_07.03.01--3d to zones/7ff90f92-dcc3-c67f-d197-82308468e8fa@2024-07-28_08.03.00--3d estimated size is 766M
send from @2024-07-28_08.03.00--3d to zones/7ff90f92-dcc3-c67f-d197-82308468e8fa@2024-07-28_09.03.00--3d estimated size is 857M
send from @2024-07-28_09.03.00--3d to zones/7ff90f92-dcc3-c67f-d197-82308468e8fa@2024-07-28_10.03.00--3d estimated size is 1.10G
total estimated size is 4.23G

....

**Comment by totalAldo** [comment]
@GernotS I have confirmed that the `-T` option is not working properly. Will review and keep you posted. If you're able to use -O by pulling on the destination, I'd be curious if that works properly for you.

**Comment by totalAldo** [comment]
@GernotS The bug has been identified. In addition, this revealed another issue where if the destination dataset did not exist, only the last snapshot on the source was being copied. The code has been updated to send the first snapshot and then replicate all subsequent snapshots. These changes have been merged into master. Please test and let me know if there are any issues with either this or the user of `parallel`

**Comment by GernotS** [comment]
This version is unable to find a common snap and thus destroyed the target:

./zxfer -FvwV  -T root@192.168.14.5 -R zones/7ff90f92-dcc3-c67f-d197-82308468e8fa copy/backup
Checking source snapshot.
Begin get_zfs_list()
New temporary file: /tmp/zxfer3lu6rb
Executing command in the background: /usr/sbin/zfs list -Hr -o name -s creation -t snapshot zones/7ff90f92-dcc3-c67f-d197-82308468e8fa
New temporary file: /tmp/zxfer0eq1uf
New temporary file: /tmp/zxfer18nddp
Running command: sed -e 's|copy/backup/7ff90f92-dcc3-c67f-d197-82308468e8fa|zones/7ff90f92-dcc3-c67f-d197-82308468e8fa|g' /tmp/zxfer0eq1uf | sort > /tmp/zxfer18nddp
Running command: /usr/bin/ssh -S /tmp/zxfer0i5d6i root@192.168.14.5 /usr/sbin/zfs list -t filesystem,volume -Hr -o name copy/backup
Waiting for background processes to finish.
Background processes finished.
New temporary file: /tmp/zxfer3i3mav
Running command: sort /tmp/zxfer3lu6rb > /tmp/zxfer3i3mav
Source dataset count:        1
End get_zfs_list()
Begin copy_filesystems()
Begin get_last_common_snapshot()
No common snapshot found, using the first source snapshot: 2023-08-05_07.17.01--1y.
End get_last_common_snapshot()
Final snapshot: zones/7ff90f92-dcc3-c67f-d197-82308468e8fa@2024-07-28_21.03.00--3d
Begin zfs_send_receive()
/usr/sbin/zfs send -v -w -I 2023-08-05_07.17.01--1y zones/7ff90f92-dcc3-c67f-d197-82308468e8fa@2024-07-28_21.03.00--3d | /usr/bin/ssh -S /tmp/zxfer0i5d6i root@192.168.14.5 "/usr/sbin/zfs receive -F copy/backup/7ff90f92-dcc3-c67f-d197-82308468e8fa"
send from @2023-08-05_07.17.01--1y to zones/7ff90f92-dcc3-c67f-d197-82308468e8fa@2023-09-05_07.17.00--1y estimated size is 23.9G

...

**Comment by totalAldo** [comment]
@GernotS Thanks for the detailed output. The issue was that the proper command was not being used to list remote destination snapshots. This is now fixed. You can try again using `-n` (dry run) to make sure nothing get's wiped. Please let me know if this latest update fixes the issue. Thanks!

**Comment by GernotS** [comment]
I can report a successful run now!

**Comment by totalAldo** [comment]
@GernotS Thanks for the detailed feedback, your replies, and patience. I just updated the experimental branch with some better exiting logic and am reviewing the `parallel` issue. I will close this issue but feel free to open another one if there are any more issues.
