### ISSUE TITLE
Reverse mode seems broken

### ISSUE THREAD

**Issue by GernotS** [totalAldo/zxfer#4]
trying to use zxfer in reverse mode:
zxfer -V -FwP -R remotepool/dataset -O "root@remotehost" localpool

See also https://shami.blog/2021/06/back-up-multiple-servers-with-zxfer/

It starts to collect snapshots and finds the last common:
End get_zfs_list()
Begin copy_filesystems()
Begin get_last_common_snapshot()
Found last common snapshot: 2024-09-16_03.13.04--1m.

But thats it then, zxfer process goes to fully load one core and doesnt start to transfer.

**Comment by totalAldo** [comment]
Hi GernotS!  

While I'm reviewing this, can you share the output of your latest commit so we're looking at the same thing:

`git log -1`


Thanks.

**Comment by GernotS** [comment]
commit d155085ae311f9e1e456a54161b6765649a8372e (HEAD -> master, origin/master, origin/development, origin/HEAD)

Merge: d892531 66b7d80

Author: Aldo Gonzalez ***@***.***>

Date:   Mon Aug 5 08:58:52 2024 -0400

 

Von: totalAldo ***@***.***> 
Gesendet: Freitag, 20. September 2024 14:37
An: totalAldo/zxfer ***@***.***>
Cc: GernotS ***@***.***>; Author ***@***.***>
Betreff: Re: [totalAldo/zxfer] Reverse mode seems broken (Issue #4)

 

Hi GernotS!

While I'm reviewing this, can you share the output of your latest commit so we're looking at the same thing:

git log -1

Thanks.

**Comment by totalAldo** [comment]
Could you please try the experimental branch. I've haven't refactored `transfer_properties()` which is the function called when using `-P` and there were some uninitialized variables from my other changes. I've initialized the variables, tested and it works for me so long as the destination dataset exists. Please let me know if it works or doesn't and if there are other issues.

Thanks for bringing this to my attention!

**Comment by GernotS** [comment]
upon first try this seems to be working.
thanks!

**Comment by totalAldo** [comment]
great! I've merged it to the main branches. If there are other issues, let me know.
